"""add override domain and reason

Revision ID: 66010eb5269c
Revises: c1bbd4e02740
Create Date: 2026-05-27 16:25:24.865949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '66010eb5269c'
down_revision: Union[str, Sequence[str], None] = 'c1bbd4e02740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('domain_id', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('override_reason', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_student_profiles_domain_id'), 'student_profiles', ['domain_id'], unique=False)
    op.create_foreign_key('fk_student_profile_domain', 'student_profiles', 'domains', ['domain_id'], ['domain_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_student_profile_domain', 'student_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_student_profiles_domain_id'), table_name='student_profiles')
    op.drop_column('student_profiles', 'override_reason')
    op.drop_column('student_profiles', 'domain_id')
    # ### end Alembic commands ###
