"""add mentor routing to exam attempt

Revision ID: 9871ffde0795
Revises: bfc157d7b64e
Create Date: 2026-05-31 11:03:46.503407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9871ffde0795'
down_revision: Union[str, Sequence[str], None] = 'bfc157d7b64e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_attempts', sa.Column('assigned_mentor_id', sa.Integer(), nullable=True))
    op.add_column('exam_attempts', sa.Column('assigned_faculty_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_exam_attempts_assigned_faculty_id'), 'exam_attempts', ['assigned_faculty_id'], unique=False)
    op.create_index(op.f('ix_exam_attempts_assigned_mentor_id'), 'exam_attempts', ['assigned_mentor_id'], unique=False)
    op.create_foreign_key(None, 'exam_attempts', 'faculty_profiles', ['assigned_faculty_id'], ['profile_id'])
    op.create_foreign_key(None, 'exam_attempts', 'mentor_profiles', ['assigned_mentor_id'], ['profile_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam_attempts', type_='foreignkey')
    op.drop_constraint(None, 'exam_attempts', type_='foreignkey')
    op.drop_index(op.f('ix_exam_attempts_assigned_mentor_id'), table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_assigned_faculty_id'), table_name='exam_attempts')
    op.drop_column('exam_attempts', 'assigned_faculty_id')
    op.drop_column('exam_attempts', 'assigned_mentor_id')
    # ### end Alembic commands ###
