"""Learning Pipeline

Revision ID: a437af958f74
Revises: d8061705808f
Create Date: 2026-05-19 00:08:04.088114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a437af958f74'
down_revision: Union[str, Sequence[str], None] = 'd8061705808f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_paths',
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.domain_id'], ),
    sa.PrimaryKeyConstraint('path_id')
    )
    op.create_index(op.f('ix_learning_paths_domain_id'), 'learning_paths', ['domain_id'], unique=False)
    op.create_index(op.f('ix_learning_paths_is_deleted'), 'learning_paths', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_learning_paths_path_id'), 'learning_paths', ['path_id'], unique=False)
    op.create_table('milestones',
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.path_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('milestone_id')
    )
    op.create_index(op.f('ix_milestones_is_deleted'), 'milestones', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_milestones_milestone_id'), 'milestones', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_milestones_path_id'), 'milestones', ['path_id'], unique=False)
    op.create_table('assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignment_type', sa.Enum('GITHUB_PR', 'FILE_UPLOAD', 'EXTERNAL_LINK', name='assignmenttype'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.milestone_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_assignments_assignment_id'), 'assignments', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignments_is_deleted'), 'assignments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_assignments_milestone_id'), 'assignments', ['milestone_id'], unique=False)
    op.create_table('milestone_resources',
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.milestone_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resources.resource_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('milestone_id', 'resource_id')
    )
    op.create_table('quizzes',
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('passing_score', sa.Integer(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.milestone_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_index(op.f('ix_quizzes_is_deleted'), 'quizzes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_quizzes_milestone_id'), 'quizzes', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_quizzes_quiz_id'), 'quizzes', ['quiz_id'], unique=False)
    op.create_table('student_progress',
    sa.Column('progress_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'PENDING_REVIEW', 'COMPLETED', 'REJECTED', name='progressstatus'), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('submission_url', sa.String(length=500), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('progress_id')
    )
    op.create_index(op.f('ix_student_progress_is_deleted'), 'student_progress', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_student_progress_item_id'), 'student_progress', ['item_id'], unique=False)
    op.create_index(op.f('ix_student_progress_item_type'), 'student_progress', ['item_type'], unique=False)
    op.create_index(op.f('ix_student_progress_progress_id'), 'student_progress', ['progress_id'], unique=False)
    op.create_index(op.f('ix_student_progress_status'), 'student_progress', ['status'], unique=False)
    op.create_index(op.f('ix_student_progress_student_id'), 'student_progress', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_progress_student_id'), table_name='student_progress')
    op.drop_index(op.f('ix_student_progress_status'), table_name='student_progress')
    op.drop_index(op.f('ix_student_progress_progress_id'), table_name='student_progress')
    op.drop_index(op.f('ix_student_progress_item_type'), table_name='student_progress')
    op.drop_index(op.f('ix_student_progress_item_id'), table_name='student_progress')
    op.drop_index(op.f('ix_student_progress_is_deleted'), table_name='student_progress')
    op.drop_table('student_progress')
    op.drop_index(op.f('ix_quizzes_quiz_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_milestone_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_is_deleted'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_table('milestone_resources')
    op.drop_index(op.f('ix_assignments_milestone_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_is_deleted'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assignment_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_milestones_path_id'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_milestone_id'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_is_deleted'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_learning_paths_path_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_is_deleted'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_domain_id'), table_name='learning_paths')
    op.drop_table('learning_paths')
    # ### end Alembic commands ###
