"""Add project progress tracking

Revision ID: af06ca75cf1f
Revises: 9871ffde0795
Create Date: 2026-06-02 10:15:41.511715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'af06ca75cf1f'
down_revision: Union[str, Sequence[str], None] = '9871ffde0795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('current_progress_level', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('current_progress_title', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('last_progress_update', sa.DateTime(), nullable=True))
    op.create_table('project_progress_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('progress_code', sa.String(length=50), nullable=False),
    sa.Column('progress_title', sa.String(length=255), nullable=False),
    sa.Column('mentor_note', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['mentor_profiles.profile_id']),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_progress_history_id'), 'project_progress_history', ['id'], unique=False)
    op.create_index(op.f('ix_project_progress_history_project_id'), 'project_progress_history', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_progress_history_updated_by'), 'project_progress_history', ['updated_by'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_progress_history_updated_by'), table_name='project_progress_history')
    op.drop_index(op.f('ix_project_progress_history_project_id'), table_name='project_progress_history')
    op.drop_index(op.f('ix_project_progress_history_id'), table_name='project_progress_history')
    op.drop_table('project_progress_history')
    op.drop_column('projects', 'last_progress_update')
    op.drop_column('projects', 'current_progress_title')
    op.drop_column('projects', 'current_progress_level')
    # ### end Alembic commands ###
