"""add assigned_mentor_id and assigned_faculty_id to student_progress

Revision ID: bfc157d7b64e
Revises: 66010eb5269c
Create Date: 2026-05-31 10:54:36.397136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bfc157d7b64e'
down_revision: Union[str, Sequence[str], None] = '66010eb5269c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_progress', sa.Column('assigned_mentor_id', sa.Integer(), nullable=True))
    op.add_column('student_progress', sa.Column('assigned_faculty_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_student_progress_assigned_faculty_id'), 'student_progress', ['assigned_faculty_id'], unique=False)
    op.create_index(op.f('ix_student_progress_assigned_mentor_id'), 'student_progress', ['assigned_mentor_id'], unique=False)
    op.create_foreign_key(None, 'student_progress', 'mentor_profiles', ['assigned_mentor_id'], ['profile_id'])
    op.create_foreign_key(None, 'student_progress', 'faculty_profiles', ['assigned_faculty_id'], ['profile_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_progress', type_='foreignkey')
    op.drop_constraint(None, 'student_progress', type_='foreignkey')
    op.drop_index(op.f('ix_student_progress_assigned_mentor_id'), table_name='student_progress')
    op.drop_index(op.f('ix_student_progress_assigned_faculty_id'), table_name='student_progress')
    op.drop_column('student_progress', 'assigned_faculty_id')
    op.drop_column('student_progress', 'assigned_mentor_id')
    # ### end Alembic commands ###
