"""Analytics and Reputation

Revision ID: c1bbd4e02740
Revises: cb8d760a7f11
Create Date: 2026-05-19 00:22:42.199941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1bbd4e02740'
down_revision: Union[str, Sequence[str], None] = 'cb8d760a7f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_type', sa.Enum('MENTOR', 'CLIENT', name='reviewertype'), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('professionalism_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('reliability_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('communication_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_student_reviews_is_deleted'), 'student_reviews', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_student_reviews_project_id'), 'student_reviews', ['project_id'], unique=False)
    op.create_index(op.f('ix_student_reviews_review_id'), 'student_reviews', ['review_id'], unique=False)
    op.create_index(op.f('ix_student_reviews_reviewer_id'), 'student_reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_student_reviews_student_id'), 'student_reviews', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_reviews_student_id'), table_name='student_reviews')
    op.drop_index(op.f('ix_student_reviews_reviewer_id'), table_name='student_reviews')
    op.drop_index(op.f('ix_student_reviews_review_id'), table_name='student_reviews')
    op.drop_index(op.f('ix_student_reviews_project_id'), table_name='student_reviews')
    op.drop_index(op.f('ix_student_reviews_is_deleted'), table_name='student_reviews')
    op.drop_table('student_reviews')
    # ### end Alembic commands ###
