"""Monitored Exams

Revision ID: cb8d760a7f11
Revises: a437af958f74
Create Date: 2026-05-19 00:12:10.811550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb8d760a7f11'
down_revision: Union[str, Sequence[str], None] = 'a437af958f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('passing_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.domain_id'], ),
    sa.PrimaryKeyConstraint('exam_id')
    )
    op.create_index(op.f('ix_exams_domain_id'), 'exams', ['domain_id'], unique=False)
    op.create_index(op.f('ix_exams_exam_id'), 'exams', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exams_is_deleted'), 'exams', ['is_deleted'], unique=False)
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Enum('MCQ', 'CODING', name='questiontype'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_questions_exam_id'), 'questions', ['exam_id'], unique=False)
    op.create_index(op.f('ix_questions_is_deleted'), 'questions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_questions_question_id'), 'questions', ['question_id'], unique=False)
    op.create_table('exam_attempts',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUBMITTED', 'UNDER_REVIEW', 'GRADED', name='examattemptstatus'), nullable=True),
    sa.Column('tab_switch_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index(op.f('ix_exam_attempts_attempt_id'), 'exam_attempts', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_exam_attempts_exam_id'), 'exam_attempts', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_attempts_is_deleted'), 'exam_attempts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_exam_attempts_status'), 'exam_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_exam_attempts_student_id'), 'exam_attempts', ['student_id'], unique=False)
    op.create_table('exam_submissions',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=False),
    sa.Column('marks_awarded', sa.Integer(), nullable=True),
    sa.Column('mentor_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.attempt_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_index(op.f('ix_exam_submissions_attempt_id'), 'exam_submissions', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_exam_submissions_is_deleted'), 'exam_submissions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_exam_submissions_question_id'), 'exam_submissions', ['question_id'], unique=False)
    op.create_index(op.f('ix_exam_submissions_submission_id'), 'exam_submissions', ['submission_id'], unique=False)
    op.create_table('monitoring_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('TAB_SWITCH', 'FULLSCREEN_EXIT', 'FOCUS_LOST', 'MEDIA_DENIED', name='monitoringeventtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.attempt_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_monitoring_logs_attempt_id'), 'monitoring_logs', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_monitoring_logs_log_id'), 'monitoring_logs', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_logs_log_id'), table_name='monitoring_logs')
    op.drop_index(op.f('ix_monitoring_logs_attempt_id'), table_name='monitoring_logs')
    op.drop_table('monitoring_logs')
    op.drop_index(op.f('ix_exam_submissions_submission_id'), table_name='exam_submissions')
    op.drop_index(op.f('ix_exam_submissions_question_id'), table_name='exam_submissions')
    op.drop_index(op.f('ix_exam_submissions_is_deleted'), table_name='exam_submissions')
    op.drop_index(op.f('ix_exam_submissions_attempt_id'), table_name='exam_submissions')
    op.drop_table('exam_submissions')
    op.drop_index(op.f('ix_exam_attempts_student_id'), table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_status'), table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_is_deleted'), table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_exam_id'), table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_attempt_id'), table_name='exam_attempts')
    op.drop_table('exam_attempts')
    op.drop_index(op.f('ix_questions_question_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_is_deleted'), table_name='questions')
    op.drop_index(op.f('ix_questions_exam_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_exams_is_deleted'), table_name='exams')
    op.drop_index(op.f('ix_exams_exam_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_domain_id'), table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###
