"""Core architecture and normalization

Revision ID: d8061705808f
Revises: 
Create Date: 2026-05-18 23:52:12.066185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8061705808f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('domain_id')
    )
    op.create_index(op.f('ix_domains_domain_id'), 'domains', ['domain_id'], unique=False)
    op.create_index(op.f('ix_domains_is_deleted'), 'domains', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_domains_name'), 'domains', ['name'], unique=True)
    op.create_table('levels',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_trust_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('level_id')
    )
    op.create_index(op.f('ix_levels_is_deleted'), 'levels', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_levels_level_id'), 'levels', ['level_id'], unique=False)
    op.create_index(op.f('ix_levels_name'), 'levels', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_index(op.f('ix_roles_is_deleted'), 'roles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=False)
    op.create_table('learning_resources',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('resource_type', sa.Enum('VIDEO', 'ARTICLE', 'COURSE', 'DOCUMENTATION', name='resourcetype'), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.domain_id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['levels.level_id'], ),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index(op.f('ix_learning_resources_domain_id'), 'learning_resources', ['domain_id'], unique=False)
    op.create_index(op.f('ix_learning_resources_is_deleted'), 'learning_resources', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_learning_resources_level_id'), 'learning_resources', ['level_id'], unique=False)
    op.create_index(op.f('ix_learning_resources_resource_id'), 'learning_resources', ['resource_id'], unique=False)
    op.create_table('skills',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.domain_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_index(op.f('ix_skills_domain_id'), 'skills', ['domain_id'], unique=False)
    op.create_index(op.f('ix_skills_is_deleted'), 'skills', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_index(op.f('ix_skills_skill_id'), 'skills', ['skill_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('admin_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_admin_profiles_is_deleted'), 'admin_profiles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_admin_profiles_profile_id'), 'admin_profiles', ['profile_id'], unique=False)
    op.create_index(op.f('ix_admin_profiles_user_id'), 'admin_profiles', ['user_id'], unique=True)
    op.create_table('client_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.domain_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_client_profiles_domain_id'), 'client_profiles', ['domain_id'], unique=False)
    op.create_index(op.f('ix_client_profiles_is_deleted'), 'client_profiles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_client_profiles_profile_id'), 'client_profiles', ['profile_id'], unique=False)
    op.create_index(op.f('ix_client_profiles_user_id'), 'client_profiles', ['user_id'], unique=True)
    op.create_table('faculty_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_faculty_profiles_is_deleted'), 'faculty_profiles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_faculty_profiles_profile_id'), 'faculty_profiles', ['profile_id'], unique=False)
    op.create_index(op.f('ix_faculty_profiles_user_id'), 'faculty_profiles', ['user_id'], unique=True)
    op.create_table('mentor_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.domain_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_mentor_profiles_domain_id'), 'mentor_profiles', ['domain_id'], unique=False)
    op.create_index(op.f('ix_mentor_profiles_is_deleted'), 'mentor_profiles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_mentor_profiles_profile_id'), 'mentor_profiles', ['profile_id'], unique=False)
    op.create_index(op.f('ix_mentor_profiles_user_id'), 'mentor_profiles', ['user_id'], unique=True)
    op.create_table('student_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('trust_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('github_handle', sa.String(length=100), nullable=True),
    sa.Column('portfolio_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.level_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_student_profiles_is_deleted'), 'student_profiles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_student_profiles_level_id'), 'student_profiles', ['level_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_profile_id'), 'student_profiles', ['profile_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True)
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'MENTOR_QA', 'COMPLETED', name='projectstatus'), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.domain_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.create_index(op.f('ix_projects_domain_id'), 'projects', ['domain_id'], unique=False)
    op.create_index(op.f('ix_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('student_skills',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'skill_id')
    )
    op.create_table('project_allocations',
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor_profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('allocation_id')
    )
    op.create_index(op.f('ix_project_allocations_allocation_id'), 'project_allocations', ['allocation_id'], unique=False)
    op.create_index(op.f('ix_project_allocations_is_deleted'), 'project_allocations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_project_allocations_mentor_id'), 'project_allocations', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_project_allocations_project_id'), 'project_allocations', ['project_id'], unique=True)
    op.create_table('project_skills',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'skill_id')
    )
    op.create_table('quality_assurance_submissions',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'MENTOR_APPROVED', 'CLIENT_REVIEWED', 'REJECTED', name='submissionstatus'), nullable=True),
    sa.Column('asset_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['student_profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_index(op.f('ix_quality_assurance_submissions_is_deleted'), 'quality_assurance_submissions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_quality_assurance_submissions_project_id'), 'quality_assurance_submissions', ['project_id'], unique=False)
    op.create_index(op.f('ix_quality_assurance_submissions_status'), 'quality_assurance_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_quality_assurance_submissions_submission_id'), 'quality_assurance_submissions', ['submission_id'], unique=False)
    op.create_index(op.f('ix_quality_assurance_submissions_submitted_by'), 'quality_assurance_submissions', ['submitted_by'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('TO_DO', 'IN_PROGRESS', 'REVIEW', 'DONE', name='taskstatus'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'), nullable=True),
    sa.Column('github_pr_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['student_profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tasks_is_deleted'), 'tasks', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=False)
    op.create_table('team_members',
    sa.Column('team_member_id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['project_allocations.allocation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('team_member_id')
    )
    op.create_index(op.f('ix_team_members_allocation_id'), 'team_members', ['allocation_id'], unique=False)
    op.create_index(op.f('ix_team_members_is_deleted'), 'team_members', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_team_members_student_id'), 'team_members', ['student_id'], unique=False)
    op.create_index(op.f('ix_team_members_team_member_id'), 'team_members', ['team_member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_members_team_member_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_student_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_is_deleted'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_allocation_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_deleted'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_quality_assurance_submissions_submitted_by'), table_name='quality_assurance_submissions')
    op.drop_index(op.f('ix_quality_assurance_submissions_submission_id'), table_name='quality_assurance_submissions')
    op.drop_index(op.f('ix_quality_assurance_submissions_status'), table_name='quality_assurance_submissions')
    op.drop_index(op.f('ix_quality_assurance_submissions_project_id'), table_name='quality_assurance_submissions')
    op.drop_index(op.f('ix_quality_assurance_submissions_is_deleted'), table_name='quality_assurance_submissions')
    op.drop_table('quality_assurance_submissions')
    op.drop_table('project_skills')
    op.drop_index(op.f('ix_project_allocations_project_id'), table_name='project_allocations')
    op.drop_index(op.f('ix_project_allocations_mentor_id'), table_name='project_allocations')
    op.drop_index(op.f('ix_project_allocations_is_deleted'), table_name='project_allocations')
    op.drop_index(op.f('ix_project_allocations_allocation_id'), table_name='project_allocations')
    op.drop_table('project_allocations')
    op.drop_table('student_skills')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.drop_index(op.f('ix_projects_domain_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_profile_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_level_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_is_deleted'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_mentor_profiles_user_id'), table_name='mentor_profiles')
    op.drop_index(op.f('ix_mentor_profiles_profile_id'), table_name='mentor_profiles')
    op.drop_index(op.f('ix_mentor_profiles_is_deleted'), table_name='mentor_profiles')
    op.drop_index(op.f('ix_mentor_profiles_domain_id'), table_name='mentor_profiles')
    op.drop_table('mentor_profiles')
    op.drop_index(op.f('ix_faculty_profiles_user_id'), table_name='faculty_profiles')
    op.drop_index(op.f('ix_faculty_profiles_profile_id'), table_name='faculty_profiles')
    op.drop_index(op.f('ix_faculty_profiles_is_deleted'), table_name='faculty_profiles')
    op.drop_table('faculty_profiles')
    op.drop_index(op.f('ix_client_profiles_user_id'), table_name='client_profiles')
    op.drop_index(op.f('ix_client_profiles_profile_id'), table_name='client_profiles')
    op.drop_index(op.f('ix_client_profiles_is_deleted'), table_name='client_profiles')
    op.drop_index(op.f('ix_client_profiles_domain_id'), table_name='client_profiles')
    op.drop_table('client_profiles')
    op.drop_index(op.f('ix_admin_profiles_user_id'), table_name='admin_profiles')
    op.drop_index(op.f('ix_admin_profiles_profile_id'), table_name='admin_profiles')
    op.drop_index(op.f('ix_admin_profiles_is_deleted'), table_name='admin_profiles')
    op.drop_table('admin_profiles')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_skill_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_is_deleted'), table_name='skills')
    op.drop_index(op.f('ix_skills_domain_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_learning_resources_resource_id'), table_name='learning_resources')
    op.drop_index(op.f('ix_learning_resources_level_id'), table_name='learning_resources')
    op.drop_index(op.f('ix_learning_resources_is_deleted'), table_name='learning_resources')
    op.drop_index(op.f('ix_learning_resources_domain_id'), table_name='learning_resources')
    op.drop_table('learning_resources')
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_is_deleted'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_levels_name'), table_name='levels')
    op.drop_index(op.f('ix_levels_level_id'), table_name='levels')
    op.drop_index(op.f('ix_levels_is_deleted'), table_name='levels')
    op.drop_table('levels')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    op.drop_index(op.f('ix_domains_is_deleted'), table_name='domains')
    op.drop_index(op.f('ix_domains_domain_id'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
